### ISSUE TITLE
Position tracking offsets rotated by head-rotation angle

### ISSUE THREAD

**Issue by jimrandomh** [cybereality/Perception#54]
First, crank up the position-tracking multiplier to a large value (10+), to exaggerate the effect. (This makes small head translations equivalent to walking across the room). Lean back, reset orientation with Shift+R, then lean forward. Then, yaw your head slightly to the left or right. Your view will translate horizontally, by a distance proportional to the forward displacement times the yaw angle. This happens because translation is applied in the reference frame of the character, after head-yaw rotation, when it should be applied before.

**Comment by DrBeef** [comment]
The problem being the rotation is already applied by the game engine by the
time we are in a position to start translating stuff. To get round that the
rotation is applied to the positional translation matrix and then the
positional translation is applied.

Don't forget that if you increase the multiplier to something very big,
then yaw rotation of the HMD is going to result in exaggerated y axis
translation simply because the front of the headset of moving left right
and forward back with the rotation (the axis of rotation is in the centre
of your head, almost, but the front of the HMD is some way off that)

Still, it's far from perfect and could do with some rework.

**Comment by jimrandomh** [comment]
This was more complicated that the description above, but it's fixed now on the "Even Number of Minus Signs" branch.
