### ISSUE TITLE
Dll injection error in Windows 10

### ISSUE THREAD

**Issue by samaust** [cybereality/Perception#79]
I'm on Windows 10. When I don't copy the d3d9.dll file to the game folder, I get an error that could be translated to "entry point not found".

![no_entry_point_found](https://cloud.githubusercontent.com/assets/10716165/13549886/3fc03eb4-e2de-11e5-8c61-e7d5fad445a4.jpg)

The strange thing is that the function mentionned is a function in d3d9.dll but the message says that it was not found in hijackdll.dll. Dll injection is complicated so I'm not sure I can fix this myself but I'll give it a look.

Is this a Windows 10 only issue ?

**Comment by mwmacmahon** [comment]
I'm also on Windows 10, so I thought I'd mention I got this error message as well when I ran a build of the master branch with no dlls in the game folder - Skyrim, for reference. Presumably it just means not all the dlls are properly hooking? I can't get the symlinks to work, so I tried copying the dlls over and then I don't get the message, although it's not working anyway - there's no vireio when I boot the game.

The latest release (3.0.1, November 2015) works fine, still. I'll try this build on a Windows 8 PC when I get the chance in the next few days... Anyway, hopefully one of the people who knows something here can help!

**Comment by samaust** [comment]
It works for me when I copy the d3d9.dll and libfreespace.dll to the game folder but I also need to keep Perception_Win32.exe open. Try to change both stereo mode and tracker. From what I can see, in the latest master, the settings in the ui reset to disabled and no tracking everytime you reopen but the settings in config.xml stay to their last saved value until you change the value in the ui.

You could try to run [DebugView++](https://github.com/djeedjay/DebugViewPP) at the same time. It will output some debug text. It might tell you what went wrong.

**Comment by baggyg** [comment]
Sorry been away the weekend and now catching up with the myriad of comms over the weekend. This is not a Windows 10 problem, and has always been this way because of the injection technique. Some games (Source / Some other engines) it is enough to just run Perception. Some engines (mainly UE3) the DLLs need to be copied to the game folder for it to hijack the process. 

You can see in the (slightly outdated) manual (https://docs.google.com/document/d/1TYpoqSjWvftbB7Z-Do02f1FXYg64DmgmT2Pqry6rgQw/edit?usp=sharing) that we tried to build up a list of what each game requires. 

Vireio will not inject if the main executable is not running. This was a feature added a year or so back as people complained that they had to remove these DLLs when they wanted to play the game without Rift. You will also see that there is a DLL installer application within Vireio which was designed to make this process of adding the DLLs simpler. 

I believe the new architecture, when complete will not suffer this problem.
