### ISSUE TITLE
Shared memory tracker not pulling x,y,z

### ISSUE THREAD

**Issue by mwmacmahon** [cybereality/Perception#80]
I'm using FreePIE to get yaw/pitch/roll/x/y/z from opentrack, but I notice that the shared memory tracker code grabs yaw/pitch/roll and only updates those. The function clearly is meant to return raw/pitch/roll/x/y/z, though, as it passes all six memory addresses! It seems like adding support for x/y/z would be as simple as taking

```
int  SharedMemoryTracker::getOrientationAndPosition(float* yaw, float* pitch, float* roll, float* x, float* y, float* z)
...
	//Initial values should now be in radians to match OVR and VRBoost requirements
	primaryYaw = pTrackBuf->Yaw;
	primaryPitch = pTrackBuf->Pitch;
	primaryRoll = pTrackBuf->Roll;
	// Then converted to Degrees
	*yaw = -RADIANS_TO_DEGREES(pTrackBuf->Yaw);
	*pitch = RADIANS_TO_DEGREES(pTrackBuf->Pitch);
	*roll = -RADIANS_TO_DEGREES(pTrackBuf->Roll);
	return 0; 
}
```

and adding

	*x = pTrackBuf->X;
	*y = pTrackBuf->Y;
	*z = pTrackBuf->Z;

Is this basic idea correct? I can't get a working setup to change/test/rebuild the program anytime soon, but if it's that quick and simple would it be possible for this to be implemented by someone working on the project?

**Comment by samaust** [comment]
I'm a new developper working on the project so I don't know all the inner workings yet. In another issue, DrBeef said :
> If VRBoost isn't present then Vireio works fine but just uses mouse emulation

You only get yaw and pitch with mouse emulation. VRBoost games are those that have a file with MTBS extension in the cfg\VRboost_rules folder with a VRboostRules setting in cfg\profiles.xml set to use the MTBS file.

Currently, from what I could see, only the following games have an MTBS file and a profile configured to use that profile to activate VRBoost :
* Dirt 3
* Dear Esther
* Fallout 3
* Fallout - New Vegas
* Grand Theft Auto 4: Episodes From Liberty Cit
* Left 4 Dead
* Left 4 Dead 2
* The Elder Scrolls V : Skyrim

Right now, adding x, y, z support to the shared memory tracker will only work in those games. To test if your fix works, it's necessary to test in a game that works with VRBoost. I never used VRBoost and headtracking in Perception so I gave a try to Fallout 3 with TrackIR, FreePIE with the VireioSMT plugin and shared memory tracker. I got mouse emulation (and it did not work well). I don't know if it's because the shared memory tracker is designed to only work in mouse emulation mode or if it's because the VRBoost profile did not work. I'm not familiar with that part of the code, I'll have to look into it.

The other developpers have been working on Perception for years, so they should be able to answer this better than me.

**Comment by mwmacmahon** [comment]
I'm testing with Skyrim, which has perfect Yaw, Pitch, and Roll from the VireioSMT plugin with VRBoost. I guess I'm mostly concerned with VRBoost, as you are correct - without it, X/Y/Z tracking are a moot point. 

Using DIY Rift mode, pressing Ctrl-H to bring up HMD stats brings up something like:
Yaw/Pitch/Roll: x.xxxx, x.xxxx, x.xxxx (all real numbers, live from headset)
x/y/z: 0.0000, 0.0000, 0.0000

While the SMTVireio drivers output:
Yaw/Pitch/Roll: x.xxxx/x.xxxx/x.xxxx (same as received by vireio)
x/y/z: x.xxxx/x.xxxx/x.xxxx (correct real-world coords in cm)

So clearly the SMTVireio drivers work fine with VRBoost!

As far as I can tell, the only reason I don't have translation support is that the guts of Perception uses the call **_getOrientationAndPosition(float* yaw, float* pitch, float* roll, float* x, float* y, float* z)_** to pull HMD coords, and for OculusTracker it returns all 6 coords, but for SharedMemoryTracker it only returns 3 and ignores the other 3 - perhaps an oversight, or a holdover from the days where VRBoost didn't support 6 coords (?). If so, it's a super easy fix!

Thanks for your response, and I'm glad to see this project is still attracting new developers!

**Comment by DrBeef** [comment]
Hello All!

Sorry, meant to say something sooner but haven't had a chance.

As Sam says, the positional isn't actually anything to do with VRBoost..
the x/y/z values are used in the transformations of the projection matrices
in the same way they are transformed to give stereo separation, the x/y/z
positional data is then subsequently used to transform the projection
matrices to give the impression of positional tracking in the world space.

VRBoost is solely responsible for the orientation (yaw/pitch/roll), and
because it is applying yaw/pitch/roll to the appropriate registers in the
game's address space, it is as good as native orientation tracking compared
to mouse emulation (which is unsatisfactory).

The reason getOrientationAndPosition only return x/y/z is only because when
I was updating this stuff for positional tracking, I only had a DK2, so
didn't go near the SharedMemoryTracker stuff.

**Comment by baggyg** [comment]
Hi all, 

Bit of confusion here but should be simple enough to clear up. Shared Memory Tracker (SMT) was a way to add support to a lot of apps like FreePIE. Instead of reading the values from a tracker it just read from a reserved memory space. 

It was completed long before positional tracking was added. Positional isn't achieved via VRBoost, but there is no reason why that should stop supporting it through the SMT. So mwmacmahon you are pretty close. From the looks of the code (https://github.com/Baristan6/VireioSMT) x,y,z are already collected, so we would need to extend Perception to update the tracking code for SMT to read the values when adjusting the projection matrices. I can't see any reason why that wouldn't work. Would seem to be a simple fix.

**Comment by mwmacmahon** [comment]
Alright, I had issues building and running the most recent version of this repository, but I managed to get a previous commit (circa end of November) to build and successfully hook into Skyrim, with the change I proposed in my original query. In other words, I added the last 3 lines before the return here:

```
int  SharedMemoryTracker::getOrientationAndPosition(float* yaw, float* pitch, float* roll, float* x, float* y, float* z)
{
#ifdef _DEBUG
	OutputDebugString("Socket Tracker getOrient\n");
#endif

	if(pTrackBuf == NULL)
		return 1;						// error no buffer

	//Initial values should now be in radians to match OVR and VRBoost requirements
	primaryYaw = pTrackBuf->Yaw;
	primaryPitch = pTrackBuf->Pitch;
	primaryRoll = pTrackBuf->Roll;
	// Then converted to Degrees
	*yaw = -RADIANS_TO_DEGREES(pTrackBuf->Yaw);
	*pitch = RADIANS_TO_DEGREES(pTrackBuf->Pitch);
	*roll = -RADIANS_TO_DEGREES(pTrackBuf->Roll);
	*x = pTrackBuf->X;
	*y = pTrackBuf->Y;
	*z = pTrackBuf->Z;


	return 0; 
}
```

To provide this input, I used a FreePIE script with this update segment (FreePIE's diagnostic output shows it is successfully changing all 6 values):

```
   vireioSMT.yaw  = Yaw - centerYaw
   vireioSMT.pitch = Pitch - centerPitch
   vireioSMT.roll = Roll - centerRoll
   vireioSMT.x = Xaxis - centerXaxis
   vireioSMT.y = Yaxis - centerYaxis
   vireioSMT.z = Zaxis - centerZaxis
```

Unfortunately, it didn't work! That is to say, ctrl-H still reveals the same problem: live updating of the angular coords from the FreePIE script, but still 0.000/0.000/0.0000 for the XYZ. This is in DIY Rift mode, for reference. Perhaps the SharedMotionTracker class needs to implement more functions from the OculusTracker, e.g. SupportsPositionTracking?

Thanks again for all the help!

**Comment by baggyg** [comment]
Line 2666 of D3DProxyDevice seems to fire off the positional update

`if (m_bPosTrackingToggle && tracker->getStatus() != MTS_LOSTPOSITIONAL
				&& !stereoView->m_disconnectedScreenView)
			{
				//Use reduced Y-position tracking in DFC mode, user should be triggering crouch by moving up and down
				float yPosition = (VRBoostValue[VRboostAxis::CameraTranslateY] / 20.0f) + tracker->primaryY;
				if (m_DuckAndCover.dfcStatus >= DAC_STANDING)
					yPosition *= 0.25f;

				m_spShaderViewAdjustment->UpdatePosition(tracker->primaryYaw, tracker->primaryPitch, tracker->primaryRoll,
					(VRBoostValue[VRboostAxis::CameraTranslateX] / 20.0f) + tracker->primaryX, 
					yPosition,
					(VRBoostValue[VRboostAxis::CameraTranslateZ] / 20.0f) + tracker->primaryZ);
			}` 

Probably worth checking all those conditionals are okay and checking the tracker values. At least you will then know whether it requires changes to the tracker or the this section.

**Comment by mwmacmahon** [comment]
Done! It was only 6 lines of code needed; none of the other OculusTracker features were needed after all. I had only forgotten to update the MemoryTracker base class' PrimaryX/Y/Z variables. I made it on a forked branch and am going to submit a pull request. I hope I'm doing this right; it's my first time trying to contribute to a github project!

```
	//Initial values should now be in radians to match OVR and VRBoost requirements
	primaryYaw = pTrackBuf->Yaw;
	primaryPitch = pTrackBuf->Pitch;
	primaryRoll = pTrackBuf->Roll;
	// Then converted to Degrees
	*yaw = -RADIANS_TO_DEGREES(pTrackBuf->Yaw);
	*pitch = RADIANS_TO_DEGREES(pTrackBuf->Pitch);
	*roll = -RADIANS_TO_DEGREES(pTrackBuf->Roll);
	// Also grab position
	primaryX = pTrackBuf->X;
	primaryY = pTrackBuf->Y;
	primaryZ = pTrackBuf->Z;
	*x = primaryX;
	*y = primaryY;
	*z = primaryZ;
```
