### ISSUE TITLE
Code missing?

### ISSUE THREAD

**Issue by ergoen** [cybereality/Perception#87]
Heya,

I've spent some time getting the code to compile under vs2017 and the latest oculus sdk. Once running I however realize that the code is not complete? It seems to depend on an "Aquilinus_x64.dll" that is not getting built! The one supplied with alpha3 is obviously not compatible with my later oculus changes (it seems to require a bunch of oculus-related files to be stored in a "My Nodes x64" folder which is also not being created during the build.
I have tried building with a "_VIREIO_3" flag instead, as that doesn't seem to require the Aquilinus, but then other parts of the code seems missing (InstallHook() doesn't point anywhere..)

Please advise :)

**Comment by EisernSchild** [comment]
Hi Attila !

Vireio v4 depends on the Aquilinus Framework. Since that is not open source
you need to take the dll files from the latest Vireio release. Please note
that the eventual driver will be released soon, then we will release
Aquilinus as well.

Regards, Denis

Am Sa., 18. Aug. 2018 um 20:41 Uhr schrieb Attila Fülöp <
notifications@github.com>:

**Comment by Moocow9m** [comment]
Any update on the Aquilinus release?

**Comment by EisernSchild** [comment]
Hi Mooncow9m !

Sorry, there is still no plan to release that whatsoever. I would have set
that to open source but since that is not my decision alone i need to ask
at the others as well. I will do so and then ping you eventually.

Regards, Denis

Am So., 25. Okt. 2020 um 23:24 Uhr schrieb Moocow9m <
notifications@github.com>:

**Comment by EisernSchild** [comment]
Aquilinus source code published, driver release still pending.
